# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.apeff <- function(discrete, beta, alpha, X, index_id, model) {
    .Call('bife_apeff', PACKAGE = 'bife', discrete, beta, alpha, X, index_id, model)
}

.apeff.corr <- function(discrete, beta, alpha, beta_start, beta_tilde, alpha_tilde, y, X, t, index_id, T_vector, model, bias_corr, iter_max1, tolerance1, iter_max2, tolerance2) {
    .Call('bife_apeff_tilde', PACKAGE = 'bife', discrete, beta, alpha, beta_start, beta_tilde, alpha_tilde, y, X, t, index_id, T_vector, model, bias_corr, iter_max1, tolerance1, iter_max2, tolerance2)
}

.bife <- function(y, X, id, beta_start, model, bias_corr, iter_max1, tolerance1, iter_max2, tolerance2) {
    .Call('bife_bife', PACKAGE = 'bife', y, X, id, beta_start, model, bias_corr, iter_max1, tolerance1, iter_max2, tolerance2)
}

